{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-2.0.0.jar",
          "url": "stringblur-2.0.0.jar",
          "size": 76769,
          "sha512": "95a92a231168d0263cbb2988debbe1b8fc361eb5c3cf5d9bc2ff76e2e3aa38a8f03450b33bc9cd632e3419d1cb42554e381cf210d6db79852f5ca78925fa0328",
          "sha256": "607273c48b51e9c8bf6e3777f4ebf34459952fa528e00453cce9d46a42241432",
          "sha1": "c936459b6a97e2144462491e0a3faca8fbe61586",
          "md5": "c48ed9b6e12407c41384cce655b7f2a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.string.plugin",
          "module": "common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-2.0.0.jar",
          "url": "stringblur-2.0.0.jar",
          "size": 76769,
          "sha512": "95a92a231168d0263cbb2988debbe1b8fc361eb5c3cf5d9bc2ff76e2e3aa38a8f03450b33bc9cd632e3419d1cb42554e381cf210d6db79852f5ca78925fa0328",
          "sha256": "607273c48b51e9c8bf6e3777f4ebf34459952fa528e00453cce9d46a42241432",
          "sha1": "c936459b6a97e2144462491e0a3faca8fbe61586",
          "md5": "c48ed9b6e12407c41384cce655b7f2a9"
        }
      ]
    }
  ]
}
