{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.20"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.20.jar",
          "url": "aabresguard-plugin-0.1.20.jar",
          "size": 23678,
          "sha512": "c4ad0406378a77e70e2d2306b4c5dd9ecba35509b0d622310ee14a61a1b75fac40441a6bd92ec08db47517f639ade53cf1bc037f8958d9917b204731f49c9e06",
          "sha256": "5c28873137002f056a0546e6803e203d84ead8dfa0b732b1d0e9a33951322271",
          "sha1": "86ac4620d056213dd2eed133db02842ceed62d59",
          "md5": "47a69db9f81f3c886dd45626d8087e07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.20"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.20.jar",
          "url": "aabresguard-plugin-0.1.20.jar",
          "size": 23678,
          "sha512": "c4ad0406378a77e70e2d2306b4c5dd9ecba35509b0d622310ee14a61a1b75fac40441a6bd92ec08db47517f639ade53cf1bc037f8958d9917b204731f49c9e06",
          "sha256": "5c28873137002f056a0546e6803e203d84ead8dfa0b732b1d0e9a33951322271",
          "sha1": "86ac4620d056213dd2eed133db02842ceed62d59",
          "md5": "47a69db9f81f3c886dd45626d8087e07"
        }
      ]
    }
  ]
}
